### ISSUE TITLE
Querrie about AESGO variable in the AE functions

### ISSUE THREAD

**Issue by Lpierott** [DanChaltiel/EDCimport#34]
For your ae's functions such as ae_table_grade_max or ae_table_soc; do you considser the variable: AESGO ( whether patients suffered of an ae before study period or no) in your calcuation?

**Comment by DanChaltiel** [comment]
No, the AE table should be filtered beforehand.
You can pipe the AE table to `dplyr::filter()` then to `ae_table_xxx()`.
But I usually filter out AEs that happen before the randomization anyway, they are not often interesting to the study... 
Of note, AEEGO is often flawed, so I wouldn't rely too much on it. 
For instance, you can try this check:
```r
df_ae %>% 
  filter(date_ae<rando_date & aeego=="No") %>% 
  edc_data_warn("AE before inclusion (and not ongoing)")
```
In most studies, you should also check the other way around.
